apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: anderson0626/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: anderson0626/client1
      context: client1
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js' 
            dest: .
